export default {
  logo: require("../assets/images/logo.png"),
  googleLogo: require("../assets/images/ic_google.png"),
  facebookLogo: require("../assets/images/ic_facebook.png"),
  appleLogo: require("../assets/images/ic_apple.png"),
  introImg: require("../assets/images/ic_1.png"),
  back: require("../assets/images/ic_back_arrow.png"),
  downArrow: require("../assets/images/ic_down.png"),
  homeIcon: require("../assets/images/ic_home.png"),
  searchIcon: require("../assets/images/ic_srch.png"),
  addIcon: require("../assets/images/ic_red_add.png"),
  notifyIcon: require("../assets/images/ic_notify.png"),
  userIcon: require("../assets/images/ic_user.png"),
  homeLogo: require("../assets/images/ic_home_icon.png"),
  locationIcon: require("../assets/images/ic_loc.png"),
  dotsIcon: require("../assets/images/ic_dots.png"),
  shareIcon: require("../assets/images/ic_direction.png"),
  logoutIcon: require("../assets/images/ic_logout.png"),
  keyIcon: require("../assets/images/ic_key.png"),
  editIcon: require("../assets/images/ic_edit.png"),
  ironMan: require("../assets/images/ironMan.jpg"),
};
