export default{
    INTRO:'Intro',
    GettingStarted:'GettingStarted',
    LOGIN: 'Login',
    SIGNUP: 'Signup',
    OTP: 'Otp',
    SET_PASSWORD: 'SetPassword',
    HOME: 'Home',
    POST_DETAILS: 'PostDetails',
    POST: 'Post',
    SEARCH_SCREEN: 'Search_Screen',
    NOTIFICATION: 'Notification',
    EDIT_PROFILE: 'EditProfile',
    PROFILE: 'Profile',
    CHANGE_PASSWORD: 'ChangePassword',
}